#!/usr/bin/env bash

die(){ # {{{
    for (( i = "${#1}"; i > 0; i-- )); do
        printf "="
    done
    printf "\n%s\n" "$1"

    local secondBreak
    secondBreak="$( for (( i = "${#0}"; i > 0; i-- )); do
        printf "="
    done)"

    echo "$secondBreak"
    echo "$0"
    echo "$secondBreak"
    exit 1
} # }}}

printVariable(){ # {{{
    local varName="$1"
    local varData="$2"
    local shouldAppendVar="$3"
    printf '# apply-crates-fixes start\n'
    # shellcheck disable=SC2015
    [[ "$shouldAppendVar" == 1 ]] && {
        printf "%s+" "$varName"
        } || {
        printf "%s" "$varName"
    }
    printf '="%b\n"\n# apply-crates-fixes end\n' "$varData"
} # }}}

printFunction(){ # {{{
    local funcData="$1"
    local funcName="$2"
    local shouldInsertFuncData="$3"
    local defaultFuncDataIfNotNew="$4"

    [[ "$shouldInsertFuncData" == 1 ]] && printf '\t'
    printf '# apply-crates-fixes start\n'
    # shellcheck disable=SC2015
    [[ "$shouldInsertFuncData" == 1 ]] && {
        printf '%b\n' "$funcData"
        } || {
        printf "%s(){\n%b\n%b\n}\n"\
            "$funcName"\
            "$funcData"\
            "$defaultFuncDataIfNotNew"
    }
    [[ "$shouldInsertFuncData" == 1 ]] && printf '\t'
    printf "# apply-crates-fixes end\n"
} # }}}

sanitizeEbuild(){ # {{{
    local filepath="$1"
    local ignoreLines=false
    while IFS='' read -r line; do
        case "$line" in
            *"# apply-crates-fixes start")
                ignoreLines=true
                ;;
            *"# apply-crates-fixes end")
                ignoreLines=false
                ;;
            *)
                $ignoreLines || {
                    printf '%s\n' "$line"
                }
                ;;
        esac
    done < "$filepath"
} # }}}

addVariableToEbuild(){ # {{{
    local filepath="$1"
    local varToCheck="$2"
    local varToAdd="$3"
    local varData="$4"
    local varLoadOrder="$5"
    local shouldAppendVar="$6"

    local mulilineVar=false
    local variablePrinted=false
    local ebuildData=""
    while IFS='' read -r line; do
        # it will currently only try to append after the variables that were assigned using `VAR=`, and not `VAR+=`,
        # however it wont technically break an ebuild, so i'm not currently implementing a fix now, which would be kinda
        # complex to implement
        case "$line" in
            "$varToCheck=\""*\")
                ebuildData="$ebuildData$line\n"
                ebuildData="$ebuildData$(
                    printVariable\
                        "$varToAdd"\
                        "$varData"\
                        "$shouldAppendVar"
                )\n"
                variablePrinted=true
                ;;
            "$varToCheck=\"")
                ebuildData="$ebuildData$line\n"
                mulilineVar=true
                ;;
            '"')
                ebuildData="$ebuildData$line\n"
                $mulilineVar && {
                    ebuildData="$ebuildData$(
                        printVariable\
                            "$varToAdd"\
                            "$varData"\
                            "$shouldAppendVar"
                    )\n"
                    variablePrinted=true
                    mulilineVar=false
                }
                ;;
            *)
                ebuildData="$ebuildData$line\n"
        esac
    done < "$filepath"
    if $variablePrinted; then
        printf "%b" "$ebuildData"
    else
        if [[ -n "$varLoadOrder" ]]; then
            firstVar="$( grep -oE '^\S+' <<< "$varLoadOrder" )"
            loadOrder="$( sed -E "s|^$firstVar ||" <<< "$varLoadOrder" )"
            # echo "'$firstVar'"
            # echo "'$loadOrder'"
            addVariableToEbuild\
                "$filepath"\
                "$firstVar"\
                "$varToAdd"\
                "$varData"\
                "$loadOrder"
        else
            echo "loadOrder is empty" 1>&2
        fi
    fi
} # }}}

insertNewFunction(){ # {{{
    local filepath="$1"
    local funcName="$2"
    local funcData="$3"
    local prevFuncLoadOrder="$4"
    local afterFuncLoadOrder="$5"
    local defaultFuncDataIfNotNew="$6"

    local needToAppend=false
    local functionToCheck=''
    for func in $prevFuncLoadOrder; do
        if grep -qE "^$func\\(\\)\\s*{" "$filepath"; then
            needToAppend=true
            functionToCheck="$func"
            break
        fi
    done
    if $needToAppend; then
        # echo "needToAppend"
        # echo "$functionToCheck"
        local functionFound=false
        while IFS='' read -r line; do
            case "$line" in
                "$functionToCheck(){"|"$functionToCheck() {")
                    printf '%s\n' "$line"
                    functionFound=true
                    ;;
                "}")
                    printf '%s\n' "$line"
                    $functionFound && {
                        functionFound=false
                        # empty lines kind of get jumbled up
                        # TODO: need to fix it
                        printf '%s\n' "$(
                            printFunction\
                                "$funcData"\
                                "$funcName"\
                                0\
                                "$defaultFuncDataIfNotNew"
                        )"
                    }
                    ;;
                *)
                    printf '%s\n' "$line"
                    ;;
            esac
        done < "$filepath"
    else
        local needToPrepend=false
        for func in $afterFuncLoadOrder; do
            if grep -qE "^$func\\(\\)\\s*{" "$filepath"; then
                needToPrepend=true
                functionToCheck="$func"
                break
            fi
        done
        if $needToPrepend; then
            # echo "needToPrepend"
            # echo "$functionToCheck"
            while IFS='' read -r line; do
                case "$line" in
                    "$functionToCheck(){"|"$functionToCheck() {")
                        printf '%s\n%s\n' "$(
                            printFunction\
                                "$funcData"\
                                "$funcName"\
                                0\
                                "$defaultFuncDataIfNotNew"
                        )" "$line"
                        ;;
                    *)
                        printf '%s\n' "$line"
                        ;;
                esac
            done < "$filepath"
        else
            cat "$filepath"
            printf '%s\n' "$(
                printFunction\
                    "$funcData"\
                    "$funcName"\
                    0\
                    "$defaultFuncDataIfNotNew"
            )"
        fi
    fi
} # }}}

prependDataToFunction(){ # {{{
    local filepath="$1"
    local funcName="$2"
    local funcData="$3"
    while IFS='' read -r line; do
        case "$line" in
            "$funcName(){"|"$funcName() {")
                printf '%s\n' "$line"
                printf '%s\n' "$( printFunction "$funcData" "$funcName" 1)"
                ;;
            *)
                printf '%s\n' "$line"
                ;;
        esac
    done < "$filepath"
} # }}}

createOrInsertFunction(){ # {{{
    local filepath="$1"
    local funcName="$2"
    local funcData="$3"
    local prevFuncLoadOrder="$4"
    local afterFuncLoadOrder="$5"
    local defaultFuncDataIfNotNew="$6"
    if grep -qE "^$funcName\\(\\)\\s*\\{" "$filepath"; then
        prependDataToFunction "$filepath" "$funcName" "$funcData"
    else
        insertNewFunction\
            "$filepath"\
            "$funcName"\
            "$funcData"\
            "$prevFuncLoadOrder"\
            "$afterFuncLoadOrder"\
            "$defaultFuncDataIfNotNew"
    fi
} # }}}

showHelp(){ # {{{
    printf "
apply-crates-fixes EBUILD_FILE_PATH

EBUILD_FILE_PATH should be the ebuild file path; passed in as an argument

depends on:
- /bin/sh executable that's a posix sh compliant shell or symlinked to one
- sort command that has --version-sort (GNU sort will do)
- sed and grep

features:
- auto fixes the ebuild
- doesn't fix the ebuild if it's not needed
- autoremoves the fixes if it detects it's not needed anymore
- implements a proper load order for inserting variables and functions and tries to maintain the order from the
  devmanual

created live on stream: https://www.youtube.com/@ingenarel

\n"
} # }}}

{ [[ -n "$1" ]] && [[ -e "$1" ]]; } || { showHelp && exit; }

mainEbuildFilePath="$(realpath "$1")"

deps=''
compileFixes=''

grep -qE '^\s*zstd-sys@' "$mainEbuildFilePath" && { # {{{
    zstd_crate_version="$(sed -nE 's|^\s*zstd@?([0-9.]+)$|\1|p' "$mainEbuildFilePath" )"
    [[ -z "$zstd_crate_version" ]] &&
    die "zstd-sys crate was detected however no zstd crate was detected"
    printf '%s\n%s' '0.12.2' "$zstd_crate_version" | sort --version-sort --check=quiet && {
        zstd_version_from_zstd_sys_crate="$(
			sed -nE 's|^\s*zstd-sys@\S+\+zstd\.(\S+)|\1|p' "$mainEbuildFilePath"
		)"
        [[ -z "$zstd_version_from_zstd_sys_crate" ]] &&
        die "couldn't get the minimum version for app-arch/zstd by trying to parse the zstd-sys crate"
        deps="$deps\n\t>=app-arch/zstd-$zstd_version_from_zstd_sys_crate"
        compileFixes="$compileFixes\texport ZSTD_SYS_USE_PKG_CONFIG=1 # fix for zstd-sys crate"
    }
} # }}}

# probably not needed:
# core-foundation-sys
# dirs-sys
# jni-sys

# TODO: (includes bundled deps, probably can fix? idk)
# aws-lc-sys (https://github.com/aws/aws-lc-rs)
# libfuzzer-sys(https://github.com/rust-fuzz/libfuzzer):
#   - needs /usr/lib/clang/22/lib/linux/libclang_rt.fuzzer-x86_64.a, clang should be a dep
# liblzma-sys (https://github.com/Portable-Network-Archive/liblzma-rs):
#   - needs xz lzma stuff?
# ring(https://crates.io/crates/ring)
#   - includes fiat something something boringssl something something, i would need to recheck

# i'm sleep deprived and can't figure out the proper way to properly use pipes and stdins and files as args so i'm using
# temporary files

sanitizeEbuild "$mainEbuildFilePath" > "$mainEbuildFilePath.sanitized"

if [[ -n "$deps" ]]; then
    addVariableToEbuild "$mainEbuildFilePath.sanitized" DEPEND DEPEND "$deps"\
        'RESTRICT PROPERTIES REQUIRED_USE IUSE KEYWORDS SLOT LICENSE SRC_URI' 1\
        > "$mainEbuildFilePath.depsfixes"
else
    cp "$mainEbuildFilePath.sanitized" "$mainEbuildFilePath.depsfixes"
fi

if [[ -n "$compileFixes" ]]; then
    createOrInsertFunction\
        "$mainEbuildFilePath.depsfixes"\
        "src_compile"\
        "src_compile"\
        "$compileFixes"\
        'src_configure src_prepare src_unpack pkg_setup pkg_nofetch pkg_pretend'\
        'src_test src_install pkg_preinst pkg_postinst pkg_prerm pkg_postrm pkg_config pkg_info'\
        '\tcargo_src_compile'\
        > "$mainEbuildFilePath.compilefixes"
else
    cp "$mainEbuildFilePath.depsfixes" "$mainEbuildFilePath.compilefixes"
fi

rm "$mainEbuildFilePath.sanitized"
rm "$mainEbuildFilePath.depsfixes"
cp "$mainEbuildFilePath.compilefixes" "$mainEbuildFilePath"
rm "$mainEbuildFilePath.compilefixes"
