#!/usr/bin/env bash

die() {
    for (( i = "${#1}"; i > 0; i-- )); do
        printf "="
    done
    printf "\n%s\n" "$1"

    secondBreak="$( for (( i = "${#0}"; i > 0; i-- )); do
        printf "="
    done)"

    echo "$secondBreak"
    echo "$0"
    echo "$secondBreak"
    exit 1
}

showHelp() {
    printf "
crdeps EBUILD_FILE_PATH LANGUAGE
EBUILD_FILE_PATH should be the ebuild file path; passed in as an argument
LANGUAGE should be the language that your trying to build the package for; passed in as an argument
supported langs are:
    - \`go\`
    - \`rust\`
in progress:
    - \`nim\`
future plans:
    - javashit stuff
    - ruby (if needed)
    - python
    - php (if needed)
This script uses the github cli to use github's release feature and upload the tarballs to it
It uses the DEPS_SCRIPT_REPO enviroment variable
If it's empty it tries to detect the remote link
If it detects the remote as ::gentoo it tries to use the DEPS_SCRIPT_GENTOO_REPO enviroment variable
Else if it detects the remote as ::guru it tries to use the DEPS_SCRIPT_GURU_REPO enviroment variable
\n"
}

{ [ -n "$1" ] && [ -e "$1" ]; } || showHelp && exit

export DISTDIR=/tmp/crdeps/distfiles
export PKGDIR=/tmp/crdeps/binpkgs
export PORTAGE_TMPDIR=/tmp/crdeps/tmp

mainEbuildFilePath="$(realpath "$1")"

[[ -z "$DEPS_SCRIPT_GITHUB_ENABLE" || "$DEPS_SCRIPT_GITHUB_ENABLE" == true ]] && {
    command -v gh > /dev/null 2>&1 || die "Please install github cli"
    gh auth status > /dev/null || {
        echo "please authenticate the github cli tool"
        gh auth login
    }
}

[[ -z "$DEPS_SCRIPT_REPO" ]] && {
    git remote -v | grep -qE '/guru[^/]+$' && {
        [[ -z "$DEPS_SCRIPT_GURU_REPO" ]] && {
            die "Please setup the DEPS_SCRIPT_GURU_REPO env"
        } || DEPS_SCRIPT_REPO="$DEPS_SCRIPT_GURU_REPO"
    } || {
        git remote -v | grep -qE '/gentoo[^/]+$' && {
            [[ -z "$DEPS_SCRIPT_GENTOO_REPO" ]] && {
                die "Please setup the DEPS_SCRIPT_GENTOO_REPO env"
            } || DEPS_SCRIPT_REPO="$DEPS_SCRIPT_GENTOO_REPO"
        } || die "couldn't figure out a valid repo for deps"
    }
}

export XZ_OPTS="-9e -T0"

package="$(echo "$1" | awk -F '/' '{print $NF}' | sed -nE 's/\/*(.+)\.([^.]+)/\1/p')"
ebuild "$1" manifest fetch unpack

packageFirst="$(echo "$package" | grep -oE '^[a-zA-Z0-9]+')"

for dir in "/var/tmp/portage/$( realpath "$1"\ | awk -F '/' '{print $(NF-2)}')/$package/work/"*; do
    [[
        "$(echo "$dir" | grep -oE "[^/]+$")" == "$packageFirst"*\
            &&
        "$(find "$dir" -maxdepth 0 -type d -empty 2>&1 | wc -l)" -lt 1
    ]]\
    &&
    {
        sourcePath="$dir"
        break
    }
done

cd "$sourcePath" || die "cd to sourcepath failed"

depfileName="$package-deps.tar.xz"
if grep -qE '^\s*inherit.+go-module.*' "$mainEbuildFilePath" || [[ "$2" == "go" ]]; then
    GOMODCACHE="$sourcePath/go-mod" go mod download -modcacherw -x ||
        die "go mod cache creation failed"

    tar --create --verbose --auto-compress --file "$package-go-mod-deps.tar.xz" "go-mod" ||
        die "go mod cache tar creation failed"

    rm -rf go-mod || die "can't remove go-mod dir"

    go mod vendor || die "go vendor creation failed"

    tar --create --verbose --auto-compress --file "$package-vendor-deps.tar.xz" "vendor" ||
        die "go vendor tar creation failed"

elif grep -qE '^\s*inherit.+cargo.*' "$mainEbuildFilePath" || [[ "$2" == "rust" ]]; then
    cargo vendor || die "cargo vendor creation failed"
    tar --create --verbose --auto-compress --file "$depfileName" "vendor" ||
        die "cargo vendor tar creation failed"
else
    die "current lang is either not support or not properly guessed"
fi

gh\
    release\
    create\
    "$depfileName"\
    ./*-deps.tar.xz\
    --repo "$DEPS_SCRIPT_REPO"\
    --latest\
    --notes "$depfileName"\
    --title "$depfileName"
